# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "FTGooglePlacesAPIExample" do

#Before push use:
pod "FTGooglePlacesAPI"

#For local development use:
#pod "FTGooglePlacesAPI", :path => "../FTGooglePlacesAPI.podspec"

end

target "FTGooglePlacesAPIExampleTests" do

end

